
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    API_KEY: '8ac94ced97e3663dea140e3ad256e274',
    API_ID:'4d16060f'
  };
